### ISSUE TITLE
lib/rest/RequestHandler not exported

### ISSUE THREAD

**Issue by zefir-git** [abalabahaha/eris#999]
```
throw new ERR_PACKAGE_PATH_NOT_EXPORTED(basePath, mappingKey);
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './lib/rest/RequestHandler' is not defined by "exports" in /home/container/node_modules/eris/package.json
at applyExports (internal/modules/cjs/loader.js:490:9)
at resolveExports (internal/modules/cjs/loader.js:506:23)
at Function.Module._findPath (internal/modules/cjs/loader.js:634:31)
at Function.Module._resolveFilename (internal/modules/cjs/loader.js:952:27)
at Function.Module._load (internal/modules/cjs/loader.js:841:27)
at Module.require (internal/modules/cjs/loader.js:1025:19)
at require (internal/modules/cjs/helpers.js:72:18)
at Object.<anonymous> (/home/container/bin/framework/RequestHandler.js:5:24)
at Module._compile (internal/modules/cjs/loader.js:1137:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10) {
code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
```
This error is thrown when I
```
const RequestHandler = require('eris/lib/rest/RequestHandler');
```
on line 5 at `/home/container/bin/framework/RequestHandler.js`

I've been trying whatnot. Any info would be highly appreciated, I'm sure I'm just doing something terribly wrong.

**Comment by bsian03** [comment]
1: fixed in #997
2: RequestHandler is already exported
3: There shouldn't be any reason why you'd need to import RequestHandler since you can use it through the client, which is a constructor parameter anyways

**Comment by zefir-git** [comment]
Sorry, I didn't quite understand. What do I need to do?

**Comment by bsian03** [comment]
```js
const RequestHandler = require("eris"). RequestHandler
```
(this is how you're supposed to import the class. regardless see below)

**Comment by bsian03** [comment]
If you're going to be using the request handler you should be going through `Client.requestHandler`.

**Comment by zefir-git** [comment]
Okay, I did that and I'm still getting the exact same error.
```
throw new ERR_PACKAGE_PATH_NOT_EXPORTED(basePath, mappingKey);
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './lib/rest/RequestHandler' is not defined by "exports" in /home/container/node_modules/eris/package.json
at applyExports (internal/modules/cjs/loader.js:490:9)
at resolveExports (internal/modules/cjs/loader.js:506:23)
at Function.Module._findPath (internal/modules/cjs/loader.js:634:31)
at Function.Module._resolveFilename (internal/modules/cjs/loader.js:952:27)
at Function.Module._load (internal/modules/cjs/loader.js:841:27)
at Module.require (internal/modules/cjs/loader.js:1025:19)
at require (internal/modules/cjs/helpers.js:72:18)
at Object.<anonymous> (/home/container/bin/framework/RequestHandler.js:5:24)
at Module._compile (internal/modules/cjs/loader.js:1137:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10) {
code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
```
And here is my full code
```
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.IMRequestHandler = void 0;
// tslint:disable-next-line: variable-name
const RequestHandler = require("eris").RequestHandler;
class IMRequestHandler extends RequestHandler {
    constructor(client, forceQueueing) {
        super(client, forceQueueing);
        this.requestStats = new Map();
    }
    request(method, url, auth, body, file, _route, short) {
        // This is similar to https://github.com/abalabahaha/eris/blob/master/lib/rest/RequestHandler.js#L46
        // but we don't actually care about rate limits, so no exceptions in grouping
        const route = url
            .replace(/\/(?:[0-9]+)/g, `/:id`)
            .replace(/\/reactions\/[^/]+/g, '/reactions/:id')
            .replace(/^\/webhooks\/(\d+)\/[A-Za-z0-9-_]{64,}/, '/webhooks/$1/:token');
        const statKey = `${method}:${route}`;
        let info = this.requestStats.get(statKey);
        if (!info) {
            info = { total: 0, succeeded: 0, errors: 0 };
            this.requestStats.set(statKey, info);
        }
        info.total++;
        return super
            .request(method, url, auth, body, file, _route, short)
            .then((res) => {
            this.requestStats.get(statKey).succeeded++;
            return res;
        })
            .catch((err) => {
            this.requestStats.get(statKey).errors++;
            throw err;
        });
    }
}
exports.IMRequestHandler = IMRequestHandler;
//# sourceMappingURL=RequestHandler.js.map
```

Is there something wrong that I am doing?

**Comment by bsian03** [comment]
If you're using TypeScript then you need to retranspile your project. But either way you should be using the request handler that eris provides, not extending it just to bypass rate limits (which in itself is an extremely bad idea).

**Comment by zefir-git** [comment]
Hmmm, this is part of this project [InviteManager](https://github.com/SideProjectGuys/invite-manager-bot/). It seems like their solution is to downgrade node subversion, which is just ridiculous.

**Comment by eritbh** [comment]
> fixed in #997

I forgot to put it back in that issue, but the conclusion we seemed to reach in #js_eris the other day was that that PR wasn't helpful and that everything should be properly exported from the main file instead. Requiring/importing custom paths shouldn't be supported.
